### ISSUE TITLE
Refactor User model

### ISSUE THREAD

**Issue by moxar** [moxar/jackmarshall#12]
The User class's implementation is bloated.

- Remove the RemindableInterface from User class.
- Create a trait UserTrait.
- Use this trait in the User class.
- Migrate the database to make the rememberMe token available

`app/models/UserTrait.php`

This trait is responsible for the remember feature

```php
trait UserTrait {
    `public function getRememberToken()
    {
        return $this->remember_token;
    }

    public function setRememberToken($value)
    {
        $this->remember_token = $value;
    }

    public function getRememberTokenName()
    {
        return 'remember_token';
    }
}
```

The new User class has no RemindableInterface and does not implement the related methods anymore (`getAuthIdentifier`, `getAuthPassword`, `getReminderEmail`).

`app/models/User.php`
```php
class User extends UserInterface {
    use UserTrait;
    ...
}
```

**Comment by elwinar** [comment]
A better name would be "RemindableTrait", as the methods that are to be embedded in the trait are related to the remindable interface.

**Comment by moxar** [comment]
Remindable is relayed to the password reminder feature, not the remember me.

See laravel 5 traits

**Comment by moxar** [comment]
The `getAuthIdentifier` has nothing to do in the `User` class. It should be deported to the `UserTrait` trait aswell.
